backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: /images 
collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "public/data/posts"
    create: true
    identifier_field: "title"
    slug: "{{fields.slug}}"
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string", pattern: ['^[a-zA-Z0-9-_]+$',
      "Alphanumeric with dashes or underscrores"]}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {label: "Image", name: "img", widget: "image", required: false}
      - { label: "Body", name: "body", widget: "markdown"}
      